BootcampDistributedSystems/Models/OrderViewModel.cs
using System;
using System.Collections.Generic;

namespace BootcampDistributedSystems.Models
{
    public class OrderViewModel
    {
        public IEnumerable<Product> Products { get; set; }

        public class Product
        {
            public String Code { get; set; }
            public String Description { get; set; }
            public Decimal Price { get; set; }
        }

        public OrderViewModel()
        {
            Products = new[]
            {
                new Product {Code = "Product01", Description = "Super Laptop", Price = 1250m},
                new Product {Code = "Product02", Description = "Super Windows Phone", Price = 450m},
                new Product {Code = "Product03", Description = "Super Windows Tablet", Price = 950m}
            };
        }
    }
}

BootcampDistributedSystems/Controllers/Demo1Controller.cs
using System.Web.Mvc;
using BootcampDistributedSystems.Handlers.PlaceOrder;
using BootcampDistributedSystems.Models;

namespace BootcampDistributedSystems.Controllers
{
    public class Demo1Controller
        : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            return View(new OrderViewModel());
        }

        [HttpPost]
        public ActionResult PlaceOrder(PlaceOrderCommand command)
        {
            var handler = new PlaceOrderHandler();
            handler.Handle(command);
            return RedirectToAction("Index", "Success");
        }
    }
}

BootcampDistributedSystems/Controllers/Demo2Controller.cs
using System.Linq;
using System.Web.Mvc;
using BootcampDistributedSystems.Handlers.PlaceOrder;
using BootcampDistributedSystems.Helpers;
using BootcampDistributedSystems.Models;

namespace BootcampDistributedSystems.Controllers
{
    public class Demo2Controller
        : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            return View(new OrderViewModel());
        }

        [HttpPost]
        public ActionResult PlaceOrder(PlaceOrderCommand command)
        {
            //Verify Command
            //Out of scope

            BusHelper.Send(new Messages.PlaceOrderDemo2Command
            {
                CustomerName = command.CustomerName,
                CustomerEmail = command.CustomerEmail,
                OrderLines = command.OrderLines.Select(ol => new Messages.PlaceOrderDemo2Command.OrderLine
                {
                    Quantity = ol.Quantity,
                    Product = new Messages.PlaceOrderDemo2Command.Product
                    {
                        Code = ol.Product.Code,
                        Description = ol.Product.Description,
                        Price = ol.Product.Price
                    }
                })
            });
            return RedirectToAction("Index", "Success");
        }
    }
}

BootcampDistributedSystems/Controllers/Demo3Controller.cs
using System.Linq;
using System.Web.Mvc;
using BootcampDistributedSystems.Handlers.PlaceOrder;
using BootcampDistributedSystems.Helpers;
using BootcampDistributedSystems.Models;

namespace BootcampDistributedSystems.Controllers
{
    public class Demo3Controller
        : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            return View(new OrderViewModel());
        }

        [HttpPost]
        public ActionResult PlaceOrder(PlaceOrderCommand command)
        {
            //Verify Command
            //Out of scope

            BusHelper.Send(new Messages.PlaceOrderDemo3Command
            {
                CustomerName = command.CustomerName,
                CustomerEmail = command.CustomerEmail,
                OrderLines = command.OrderLines.Select(ol => new Messages.PlaceOrderDemo3Command.OrderLine
                {
                    Quantity = ol.Quantity,
                    Product = new Messages.PlaceOrderDemo3Command.Product
                    {
                        Code = ol.Product.Code,
                        Description = ol.Product.Description,
                        Price = ol.Product.Price
                    }
                })
            });
            return RedirectToAction("Index", "Success");
        }
    }
}

BootcampDistributedSystems/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BootcampDistributedSystems.Controllers
{
    public class HomeController 
        : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

BootcampDistributedSystems/Controllers/SuccessController.cs
using System.Web.Mvc;

namespace BootcampDistributedSystems.Controllers
{
    public class SuccessController
        : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

BootcampDistributedSystems/Views/Demo1/Index.cshtml
@model BootcampDistributedSystems.Models.OrderViewModel
@{
    ViewBag.Title = "Shop shop";
}

<div >
    <h1>Place an order</h1>
    <form action="@Url.Action("PlaceOrder","Demo1")" method="POST">
        <table class="table table-responsive">
            <thead>
                <tr>
                    <th>Description</th>
                    <th>Price</th>
                    <th>Quantity</th>
                </tr>
            </thead>
            <tbody>
                
                @{
                    var i = 0;
                    foreach (var product in Model.Products)
                    {
                        <tr>
                            <td>@product.Description</td>
                            <td>@product.Price</td>
                            <td>
                                <input type="text" name="OrderLines[@i].Quantity" class="form-control" placeholder="Quantity">
                                <input type="hidden" name="OrderLines[@i].Product.Code" value="@product.Code">
                                <input type="hidden" name="OrderLines[@i].Product.Price" value="@product.Price">
                                <input type="hidden" name="OrderLines[@i].Product.Description" value="@product.Description">
                            </td>
                        </tr>
                        i++;
                    }
                }
            </tbody>
        </table>
        <div class="form-group">
            <label for="customerName">Name</label>
            <input type="text" class="form-control" id="customerName" placeholder="Enter your name" name="CustomerName">
        </div>        
        <div class="form-group">
            <label for="customerEmail">Email address</label>
            <input type="email" class="form-control" id="customerEmail" placeholder="Enter email" name="CustomerEmail">
        </div>
        <p>
            <button type="submit" class="btn btn-primary btn-lg">Order now!</button>
        </p>
    </form>
</div>

BootcampDistributedSystems/Views/Demo2/Index.cshtml
@model BootcampDistributedSystems.Models.OrderViewModel
@{
    ViewBag.Title = "Shop shop";
}

<div >
    <h1>Place an order</h1>
    <form action="@Url.Action("PlaceOrder","Demo2")" method="POST">
        <table class="table table-responsive">
            <thead>
                <tr>
                    <th>Description</th>
                    <th>Price</th>
                    <th>Quantity</th>
                </tr>
            </thead>
            <tbody>
                
                @{
                    var i = 0;
                    foreach (var product in Model.Products)
                    {
                        <tr>
                            <td>@product.Description</td>
                            <td>@product.Price</td>
                            <td>
                                <input type="text" name="OrderLines[@i].Quantity" class="form-control" placeholder="Quantity">
                                <input type="hidden" name="OrderLines[@i].Product.Code" value="@product.Code">
                                <input type="hidden" name="OrderLines[@i].Product.Price" value="@product.Price">
                                <input type="hidden" name="OrderLines[@i].Product.Description" value="@product.Description">
                            </td>
                        </tr>
                        i++;
                    }
                }
            </tbody>
        </table>
        <div class="form-group">
            <label for="customerName">Name</label>
            <input type="text" class="form-control" id="customerName" placeholder="Enter your name" name="CustomerName">
        </div>        
        <div class="form-group">
            <label for="customerEmail">Email address</label>
            <input type="email" class="form-control" id="customerEmail" placeholder="Enter email" name="CustomerEmail">
        </div>
        <p>
            <button type="submit" class="btn btn-primary btn-lg">Order now!</button>
        </p>
    </form>
</div>

BootcampDistributedSystems/Views/Demo3/Index.cshtml
@model BootcampDistributedSystems.Models.OrderViewModel
@{
    ViewBag.Title = "Shop shop";
}

<div >
    <h1>Place an order</h1>
    <form action="@Url.Action("PlaceOrder","Demo3")" method="POST">
        <table class="table table-responsive">
            <thead>
                <tr>
                    <th>Description</th>
                    <th>Price</th>
                    <th>Quantity</th>
                </tr>
            </thead>
            <tbody>
                
                @{
                    var i = 0;
                    foreach (var product in Model.Products)
                    {
                        <tr>
                            <td>@product.Description</td>
                            <td>@product.Price</td>
                            <td>
                                <input type="text" name="OrderLines[@i].Quantity" class="form-control" placeholder="Quantity">
                                <input type="hidden" name="OrderLines[@i].Product.Code" value="@product.Code">
                                <input type="hidden" name="OrderLines[@i].Product.Price" value="@product.Price">
                                <input type="hidden" name="OrderLines[@i].Product.Description" value="@product.Description">
                            </td>
                        </tr>
                        i++;
                    }
                }
            </tbody>
        </table>
        <div class="form-group">
            <label for="customerName">Name</label>
            <input type="text" class="form-control" id="customerName" placeholder="Enter your name" name="CustomerName">
        </div>        
        <div class="form-group">
            <label for="customerEmail">Email address</label>
            <input type="email" class="form-control" id="customerEmail" placeholder="Enter email" name="CustomerEmail">
        </div>
        <p>
            <button type="submit" class="btn btn-primary btn-lg">Order now!</button>
        </p>
    </form>
</div>

BootcampDistributedSystems/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>QFrame NV Shop</h1>
    <p class="lead">Met allerlei fantastische producten.</p>
    <p><a href="@Url.Action("Index","Demo1")" class="btn btn-primary btn-lg">Start shopping!</a></p>
</div>

BootcampDistributedSystems/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("QFrame Shop", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Demo 1", "Index", "Demo1")</li>
                    <li>@Html.ActionLink("Demo 2", "Index", "Demo2")</li>
                    <li>@Html.ActionLink("Demo 3", "Index", "Demo3")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

BootcampDistributedSystems/Views/Success/Index.cshtml
@{
    ViewBag.Title = "Order placed";
}

<div class="jumbotron">
    <h1>Order successful</h1>
    <p class="lead">Thank you come again!</p>
</div>